### ISSUE TITLE
Possible to toggle some icon in the sizebar invisible or visible?

### ISSUE THREAD

**Issue by Quorafind** [phibr0/obsidian-customizable-sidebar#3]
Is it doable?

**Comment by phibr0** [comment]
I will think about it. In the meantime you can do that by using the following CSS Snippet:

```css
.side-dock-ribbon-action[aria-label="<Command Name>"] {
    display: none;
}
```

Just replace the `<Command Name>` with what you see when you hover over the Command:

![image](https://user-images.githubusercontent.com/59741989/129472844-9bda443b-5066-4ff2-84c7-98fe7c270c6e.png)
